language: node_js
node_js:
  - "12.16.2"
install:
  - "npm install"
before_script:
  - "npm run build"
  - "npm start &"
script:
  - "npm test"
service_name: travis-pro
repo_token: UBoTdz1Of7PlNM8BXFbyMuCaK1qG9j9jE
